version: "3.9"

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres # Specify the name of the database to be created
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  data: